import type { Metadata } from "next";
import CssBaseine from "@mui/material/CssBaseline";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <CssBaseine />
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
